name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. This "clones" your code so the runner can see your .sh file
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. This gives the runner permission to run the file and then executes it
      - name: Run bash script from repo
        run: |
          chmod +x ./myscript.sh
          ./myscript.sh